cc_library(
    name = "json",
    visibility = [
      "//visibility:public",
    ],
    srcs = [
      "json_value.cc",
      "json_reader.cc",
      "json_writer.cc",
    ],
    hdrs = [
      "json_valueiterator.inl",
      "json_tool.h",
      "json/allocator.h",
      "json/assertions.h",
      "json/config.h",
      "json/forwards.h",
      "json/json.h",
      "json/json_features.h",
      "json/reader.h",
      "json/value.h",
      "json/version.h",
      "json/writer.h",
    ],
)
